

import { Language, Translation, Team, Player } from './types';

export const STARTING_SEASONS = [
  "2024/2025",
  "2025/2026",
  "2026/2027",
  "2027/2028"
];

export const MOCK_PLAYERS: Player[] = [
  { id: '1', name: 'Thibaut Courtois', age: 31, overall: 90, position: 'GK', nationality: 'Belgium', value: 60000000, wage: 250000, isHomegrown: false, isNonEU: false },
  { id: '2', name: 'Vinícius Jr.', age: 23, overall: 89, position: 'LW', nationality: 'Brazil', value: 120000000, wage: 300000, isHomegrown: false, isNonEU: true },
  { id: '3', name: 'Jude Bellingham', age: 20, overall: 87, position: 'CAM', nationality: 'England', value: 110000000, wage: 200000, isHomegrown: false, isNonEU: true },
  { id: '4', name: 'Nacho Fernández', age: 34, overall: 82, position: 'CB', nationality: 'Spain', value: 8000000, wage: 90000, isHomegrown: true, isNonEU: false },
  { id: '5', name: 'Federico Valverde', age: 25, overall: 88, position: 'CM', nationality: 'Uruguay', value: 90000000, wage: 180000, isHomegrown: false, isNonEU: true },
  { id: '6', name: 'Dani Carvajal', age: 32, overall: 84, position: 'RB', nationality: 'Spain', value: 15000000, wage: 110000, isHomegrown: true, isNonEU: false },
  { id: '7', name: 'Rodrygo', age: 23, overall: 85, position: 'RW', nationality: 'Brazil', value: 70000000, wage: 160000, isHomegrown: false, isNonEU: true },
  { id: '8', name: 'Eduardo Camavinga', age: 21, overall: 82, position: 'CDM', nationality: 'France', value: 60000000, wage: 100000, isHomegrown: false, isNonEU: false },
  { id: '9', name: 'Luka Modrić', age: 38, overall: 86, position: 'CM', nationality: 'Croatia', value: 5000000, wage: 190000, isHomegrown: false, isNonEU: false },
  { id: '10', name: 'Fran García', age: 24, overall: 78, position: 'LB', nationality: 'Spain', value: 20000000, wage: 60000, isHomegrown: true, isNonEU: false },
];

export const MOCK_TEAMS: Team[] = [
  {
    id: 't1',
    name: 'Real Madrid',
    league: 'La Liga',
    transferBudget: 120000000,
    wageBudget: 4500000,
    players: MOCK_PLAYERS
  },
  {
    id: 't2',
    name: 'Manchester City',
    league: 'Premier League',
    transferBudget: 180000000,
    wageBudget: 5500000,
    players: [
       { id: '11', name: 'Erling Haaland', age: 23, overall: 91, position: 'ST', nationality: 'Norway', value: 150000000, wage: 400000, isHomegrown: false, isNonEU: false },
       { id: '12', name: 'Phil Foden', age: 23, overall: 86, position: 'RW', nationality: 'England', value: 90000000, wage: 200000, isHomegrown: true, isNonEU: true }, 
       { id: '13', name: 'Kevin De Bruyne', age: 32, overall: 91, position: 'CM', nationality: 'Belgium', value: 60000000, wage: 350000, isHomegrown: false, isNonEU: false },
       { id: '14', name: 'Rico Lewis', age: 19, overall: 76, position: 'RB', nationality: 'England', value: 15000000, wage: 40000, isHomegrown: true, isNonEU: true },
    ]
  },
  {
    id: 't3',
    name: 'Como 1907',
    league: 'Serie A',
    transferBudget: 15000000,
    wageBudget: 500000,
    players: [
       { id: '21', name: 'Patrick Cutrone', age: 26, overall: 74, position: 'ST', nationality: 'Italy', value: 6000000, wage: 30000, isHomegrown: true, isNonEU: false },
       { id: '22', name: 'Alessandro Gabrielloni', age: 29, overall: 70, position: 'ST', nationality: 'Italy', value: 2000000, wage: 15000, isHomegrown: false, isNonEU: false }
    ]
  }
];

export const TRANSLATIONS: Record<Language, Translation> = {
  [Language.EN]: {
    welcome: "Welcome to MCM+",
    subtitle: "Manage your FC career like a pro.",
    login: "Log In",
    register: "Sign Up",
    email: "Email Address",
    password: "Password",
    confirmPassword: "Confirm Password",
    submitLogin: "Log In",
    submitRegister: "Create Account",
    haveAccount: "Already have an account?",
    noAccount: "Don't have an account?",
    switchLogin: "Log in here",
    switchRegister: "Register here",
    loading: "Processing...",
    errorGeneric: "Something went wrong. Please check your credentials.",
    successLogin: "Successfully logged in!",
    signOut: "Sign Out",
    secureAccess: "Secure Access",
    newCareer: "New Career",

    // Dashboard
    hello: "Hello",
    searchPlaceholder: "Search players, teams...",
    continueCareer: "Active Career",

    // Nav
    navHome: "Home",
    navSquad: "Squad",
    navClub: "Club",
    navMarket: "Market",
    navSettings: "Settings",

    // App
    workInProgress: "Work in Progress",

    // Profile
    accountSettings: "Account Settings",
    editProfile: "Edit Profile",
    nickname: "Nickname",
    changeAvatar: "Change Photo",
    deleteAvatar: "Remove Photo",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    deleteConfirmTitle: "Delete Photo?",
    deleteConfirmMessage: "Are you sure you want to delete your profile photo? This cannot be undone.",
    confirm: "Confirm",

    // Settings
    appSettings: "App Settings",
    language: "Language",
    theme: "Appearance",
    currency: "Currency",
    themeLight: "Light",
    themeDark: "Dark",
    themeAuto: "System",
    clubCustomization: "Club Customization",
    teamLogo: "Team Crest",
    uploadLogo: "Upload Crest",
    uploadLogoDesc: "Upload a transparent PNG (max 1MB).",
    deleteLogoConfirm: "Remove Crest?",
    deleteLogoMessage: "Are you sure you want to remove the team crest?",
    replaceLogo: "Replace",

    // Career Creation & Stats
    startCareer: "Start New Career",
    managerName: "Manager Name",
    selectTeam: "Select Team",
    customTeam: "Create Custom Team",
    teamName: "Team Name",
    createCareer: "Create Career",
    transferBudget: "Transfer Budget",
    wageBudget: "Wage Budget",
    editTransferBudget: "Edit Transfer Budget",
    editWageBudget: "Edit Wage Budget",
    weekly: "Weekly",
    yearly: "Yearly",
    weeklySuffix: "/wk",
    yearlySuffix: "/yr",
    squadSize: "Squad Size",
    avgAge: "Avg Age",
    avgOvr: "Avg OVR",
    over22: "Over 22",
    homegrown: "Homegrown",
    nonEU: "Non-EU",
    statsOverview: "Squad Overview",
    financials: "Financials",
    financialActivity: "Season Financials",
    history: "Transaction History",
    trends: "Financial Trends",
    noActivity: "No transactions yet",
    latestTransaction: "Latest Activity",
    viewFullHistory: "View Full History",
    transferTrend: "Transfer Budget Trend",
    wageTrend: "Wage Budget Trend",
    clickToView: "Click to view detailed charts",
    trendsResetMessage: "Trends are reset at the end of each season.",

    // Season & Actions
    currentSeason: "Current Season",
    startSeason: "Starting Season",
    endSeason: "End Season (+1 Age)",
    deleteCareer: "Delete Career",
    deleteCareerTitle: "Delete Career?",
    deleteCareerMessage: "Are you sure you want to delete this career? All data will be lost permanently.",
    endSeasonConfirmTitle: "End Season?",
    endSeasonConfirmMessage: "This will advance the season, increase players' age, and RESET financial history. Do you want to continue?",
    seasonAdvanced: "Season advanced!",
    managerActions: "Manager Actions",
    confirmChangeTeam: "Confirm & Change Team",
    newTeamName: "New Team Name",
    changeTeamTitle: "Change Team",
    enterNewTeamName: "Enter the name of your new team",

    // Squad & AI Import
    addPlayer: "Add Player",
    addManual: "Add Manually",
    addPlayerTitle: "Add New Player",
    importPlayers: "AI Import",
    aiScan: "Scan Image",
    aiScanDesc: "Take a photo of your squad screen (FC25/24). The AI will extract player data.",
    pasteText: "Paste Text",
    pasteTextDesc: "Paste a list of players from SoFifa, Futbin or a text file.",
    uploadImage: "Upload Image",
    analyze: "Analyze with Gemini AI",
    analyzing: "AI is analyzing...",
    importSuccess: "Players imported successfully!",
    noPlayersFound: "No players found. Try a clearer image or text.",
    confirmImport: "Confirm Import",
    discard: "Discard",
    positionGK: "Goalkeepers",
    positionDEF: "Defenders",
    positionMID: "Midfielders",
    positionFWD: "Forwards",
    positionLoan: "On Loan",
    onLoan: "Loaned Out",
    editPlayer: "Edit Player",
    releasePlayer: "Release Player",
    releaseConfirmTitle: "Release Player?",
    releaseConfirmMessage: "Are you sure? This will remove the player from your squad.",
    labelName: "Name",
    labelAge: "Age",
    labelOverall: "Overall",
    labelRole: "Role / Position",
    playersCount: "Players",
    loanedCount: "Loaned",

    // Market
    buyPlayer: "Buy Player",
    sellPlayer: "Sell Players",
    signingModalTitle: "Sign New Player",
    sellingModalTitle: "Sell Player",
    selectPlayerToSell: "Select Player to Sell",
    playerName: "Player Name",
    transferFee: "Transfer Fee",
    wage: "Weekly Wage",
    saleFee: "Sale Fee",
    releasedWage: "Released Wage (Weekly)",
    confirmSigning: "Confirm Signing",
    confirmSale: "Confirm Sale",
    fundsError: "Insufficient funds!",
    bought: "Bought",
    sold: "Sold",

    // Club View
    clubOverview: "Club Overview",
    trophyCabinet: "Trophy Cabinet",
    addTrophy: "Add Trophy",
    addTrophyPlaceholder: "e.g. Champions League 2026",
    seasonalEvents: "Seasonal Events",
    preMatchEvents: "Pre-Match Events",
    generateEvent: "Generate with AI",
    activeEvents: "Active Events",
    maxEventsReached: "Max Limit Reached",
    aiEventGenerator: "AI Event Generator",
    regenerate: "Regenerate",
    saveEvent: "Save Event",
    deleteEventConfirm: "Delete Event?",
    deleteEventMessage: "Do you want to remove this active event?"
  },
  [Language.IT]: {
    welcome: "Benvenuto su MCM+",
    subtitle: "Gestisci la tua carriera FC come un professionista.",
    login: "Accedi",
    register: "Registrati",
    email: "Indirizzo Email",
    password: "Password",
    confirmPassword: "Conferma Password",
    submitLogin: "Accedi",
    submitRegister: "Crea Account",
    haveAccount: "Hai già un account?",
    noAccount: "Non hai un account?",
    switchLogin: "Accedi qui",
    switchRegister: "Registrati qui",
    loading: "Elaborazione in corso...",
    errorGeneric: "Qualcosa è andato storto. Controlla le tue credenziali.",
    successLogin: "Accesso effettuato con successo!",
    signOut: "Disconnetti",
    secureAccess: "Accesso Sicuro",
    newCareer: "Nuova Carriera",

    // Dashboard
    hello: "Ciao",
    searchPlaceholder: "Cerca giocatori, squadre...",
    continueCareer: "Carriera Attiva",

    // Nav
    navHome: "Home",
    navSquad: "Rosa",
    navClub: "Club",
    navMarket: "Mercato",
    navSettings: "Impostazioni",

    // App
    workInProgress: "Lavori in corso",

    // Profile
    accountSettings: "Impostazioni Account",
    editProfile: "Modifica Profilo",
    nickname: "Nickname",
    changeAvatar: "Cambia Foto",
    deleteAvatar: "Rimuovi Foto",
    saveChanges: "Salva Modifiche",
    cancel: "Annulla",
    deleteConfirmTitle: "Eliminare Foto?",
    deleteConfirmMessage: "Sei sicuro di voler eliminare la tua foto profilo? Questa azione non può essere annullata.",
    confirm: "Conferma",

    // Settings
    appSettings: "Impostazioni App",
    language: "Lingua",
    theme: "Aspetto",
    currency: "Valuta",
    themeLight: "Chiaro",
    themeDark: "Scuro",
    themeAuto: "Sistema",
    clubCustomization: "Personalizzazione Club",
    teamLogo: "Stemma Club",
    uploadLogo: "Carica Stemma",
    uploadLogoDesc: "Carica un PNG trasparente (max 1MB).",
    deleteLogoConfirm: "Rimuovere Stemma?",
    deleteLogoMessage: "Sei sicuro di voler rimuovere lo stemma della squadra?",
    replaceLogo: "Sostituisci",

    // Career Creation & Stats
    startCareer: "Inizia Nuova Carriera",
    managerName: "Nome Allenatore",
    selectTeam: "Seleziona Squadra",
    customTeam: "Crea Squadra Personalizzata",
    teamName: "Nome Squadra",
    createCareer: "Crea Carriera",
    transferBudget: "Budget Trasferimenti",
    wageBudget: "Budget Stipendi",
    editTransferBudget: "Modifica Budget Trasferimenti",
    editWageBudget: "Modifica Budget Stipendi",
    weekly: "Settimanale",
    yearly: "Annuale",
    weeklySuffix: "/wk",
    yearlySuffix: "/yr",
    squadSize: "Rosa",
    avgAge: "Età Media",
    avgOvr: "OVR Medio",
    over22: "Over 22",
    homegrown: "Vivaio",
    nonEU: "Extra-UE",
    statsOverview: "Riepilogo Rosa",
    financials: "Finanze",
    financialActivity: "Attività Finanziaria",
    history: "Storico Transazioni",
    trends: "Andamento Finanziario",
    noActivity: "Nessuna transazione recente",
    latestTransaction: "Ultima Operazione",
    viewFullHistory: "Vedi Storico Completo",
    transferTrend: "Andamento Budget Trasferimenti",
    wageTrend: "Andamento Budget Stipendi",
    clickToView: "Clicca per i grafici dettagliati",
    trendsResetMessage: "I grafici vengono resettati alla fine di ogni stagione.",

    // Season & Actions
    currentSeason: "Stagione Corrente",
    startSeason: "Stagione di Partenza",
    endSeason: "Termina Stagione (+1 Età)",
    deleteCareer: "Elimina Carriera",
    deleteCareerTitle: "Eliminare Carriera?",
    deleteCareerMessage: "Sei sicuro di voler eliminare questa carriera? Tutti i dati andranno persi per sempre.",
    endSeasonConfirmTitle: "Terminare Stagione?",
    endSeasonConfirmMessage: "Passerai alla stagione successiva, l'età dei giocatori aumenterà e lo STORICO FINANZIARIO verrà resettato. Continuare?",
    seasonAdvanced: "Stagione avanzata!",
    managerActions: "Azioni Manager",
    confirmChangeTeam: "Conferma e Cambia Squadra",
    newTeamName: "Nome Nuova Squadra",
    changeTeamTitle: "Cambio Squadra",
    enterNewTeamName: "Inserisci il nome della nuova squadra",

    // Squad & AI Import
    addPlayer: "Aggiungi",
    addManual: "Aggiungi Manualmente",
    addPlayerTitle: "Aggiungi Giocatore",
    importPlayers: "Importa con AI",
    aiScan: "Scansiona Immagine",
    aiScanDesc: "Fai una foto alla schermata della rosa (FC25/24). L'AI estrarrà i dati.",
    pasteText: "Incolla Testo",
    pasteTextDesc: "Incolla una lista di giocatori da SoFifa, Futbin o testo.",
    uploadImage: "Carica Immagine",
    analyze: "Analizza con Gemini AI",
    analyzing: "L'AI sta analizzando...",
    importSuccess: "Giocatori importati con successo!",
    noPlayersFound: "Nessun giocatore trovato. Prova un'immagine più chiara.",
    confirmImport: "Conferma Importazione",
    discard: "Annulla",
    positionGK: "Portieri",
    positionDEF: "Difensori",
    positionMID: "Centrocampisti",
    positionFWD: "Attaccanti",
    positionLoan: "In Prestito",
    onLoan: "In Prestito",
    editPlayer: "Modifica",
    releasePlayer: "Svincola",
    releaseConfirmTitle: "Svincolare Giocatore?",
    releaseConfirmMessage: "Sei sicuro? Il giocatore verrà rimosso dalla rosa.",
    labelName: "Nome",
    labelAge: "Età",
    labelOverall: "Overall",
    labelRole: "Ruolo / Posizione",
    playersCount: "Giocatori",
    loanedCount: "In Prestito",
    
    // Market
    buyPlayer: "Acquista",
    sellPlayer: "Cessioni",
    signingModalTitle: "Acquisto Giocatore",
    sellingModalTitle: "Cessione Giocatore",
    selectPlayerToSell: "Seleziona Giocatore da Cedere",
    playerName: "Nome e Cognome",
    transferFee: "Costo Cartellino",
    wage: "Ingaggio (Settimanale)",
    saleFee: "Cifra Cessione",
    releasedWage: "Ingaggio Liberato (Settimanale)",
    confirmSigning: "Conferma Acquisto",
    confirmSale: "Conferma Cessione",
    fundsError: "Fondi insufficienti!",
    bought: "Acquisto",
    sold: "Cessione",

    // Club View
    clubOverview: "Panoramica Club",
    trophyCabinet: "Palmares",
    addTrophy: "Aggiungi Trofeo",
    addTrophyPlaceholder: "es. Champions League 2026",
    seasonalEvents: "Imprevisti Stagionali",
    preMatchEvents: "Imprevisti Pre-Partita",
    generateEvent: "Genera con AI",
    activeEvents: "Eventi Attivi",
    maxEventsReached: "Limite Raggiunto",
    aiEventGenerator: "Generatore AI",
    regenerate: "Rigenera",
    saveEvent: "Salva Evento",
    deleteEventConfirm: "Eliminare Evento?",
    deleteEventMessage: "Vuoi rimuovere questo evento attivo?"
  }
};